trigger:
- "*"

pool:
  vmImage: ubuntu-latest

steps:
- task: mirror-git-repository-vsts-task@1
  inputs:
    sourceGitRepositoryUri: 'https://github.com/zachhols/navcontainerhelper.git'
    # sourceGitRepositoryPersonalAccessToken: '$(ghp)'
    destinationGitRepositoryUri: 'https://dev.azure.com/tfs-lsretail/Project%20Asterix/_git/navcontainerhelper-private'
    destinationGitRepositoryPersonalAccessToken: '$(adp)'